/* This file was generated by the Hex-Rays decompiler version 9.3.0.260213.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Data declarations

// extern void (__stdcall *ExFreePoolWithTag)(PVOID P, ULONG Tag);


//----- (0000000140001000) ----------------------------------------------------
__int64 __fastcall sub_140001000(__int64 a1, IRP *a2)
{
  a2->IoStatus.Status = 0;
  a2->IoStatus.Information = 0;
  IofCompleteRequest(a2, 0);
  return 0;
}

//----- (0000000140001020) ----------------------------------------------------
__int64 __fastcall sub_140001020(__int64 a1, IRP *a2)
{
  struct _IO_STACK_LOCATION *CurrentStackLocation; // rcx
  struct _IRP *MasterIrp; // rax
  unsigned int v5; // edi

  CurrentStackLocation = a2->Tail.Overlay.CurrentStackLocation;
  MasterIrp = a2->AssociatedIrp.MasterIrp;
  v5 = -1073741823;
  if ( CurrentStackLocation->Parameters.Read.ByteOffset.LowPart == 2236436 )
  {
    if ( MasterIrp && CurrentStackLocation->Parameters.Create.Options == 4 )
      v5 = TerminateProcess(*(unsigned int *)&MasterIrp->Type);
    else
      v5 = -1073741306;
  }
  a2->IoStatus.Information = 0;
  a2->IoStatus.Status = v5;
  IofCompleteRequest(a2, 0);
  return v5;
}
// 14000198C: using guessed type __int64 __fastcall sub_14000198C(_QWORD);

//----- (0000000140001084) ----------------------------------------------------
__int64 __fastcall sub_140001084(__int64 a1, IRP *a2)
{
  if ( !KeGetCurrentIrql() )
    InstallLenovoServices();
  a2->IoStatus.Status = 0;
  a2->IoStatus.Information = 0;
  IofCompleteRequest(a2, 0);
  return 0;
}
// 1400010E0: using guessed type __int64 sub_1400010E0(void);

//----- (00000001400010B8) ----------------------------------------------------
NTSTATUS __fastcall au_re_KeDelayExecutionThread(int ms)
{
  union _LARGE_INTEGER Interval; // [rsp+38h] [rbp+10h] BYREF

  Interval.QuadPart = -10000LL * ms;
  return KeDelayExecutionThread(0, 0, &Interval);
}

//----- (00000001400010E0) ----------------------------------------------------
__int64 InstallLenovoServices()
{
  int STATUS; // esi
  unsigned int v2; // eax
  _WORD *v3; // rcx
  __int64 v4; // rdx
  __int16 v5; // ax
  char *v6; // rax
  __int64 v7; // rdi
  __int64 v8; // rax
  _WORD *v9; // rcx
  _WORD *v10; // rcx
  __int64 v11; // rdx
  __int16 v12; // ax
  char *v13; // rcx
  __int64 v14; // rax
  _WORD *v15; // rcx
  _WORD *v16; // rcx
  __int64 v17; // rdx
  __int16 v18; // ax
  char *v19; // rcx
  char *v20; // rcx
  char *v21; // rcx
  char *v22; // rcx
  char *v23; // rcx
  char *v24; // rcx
  char *v25; // rcx
  char *v26; // rcx
  SIZE_T v27; // [rsp+28h] [rbp-E0h]
  SIZE_T v28; // [rsp+28h] [rbp-E0h]
  SIZE_T v29; // [rsp+28h] [rbp-E0h]
  SIZE_T v30; // [rsp+28h] [rbp-E0h]
  __int64 Data; // [rsp+38h] [rbp-D0h] BYREF
  PVOID InstallPath; // [rsp+40h] [rbp-C8h] BYREF
  WCHAR SourceString[520]; // [rsp+48h] [rbp-C0h] BYREF
  __int64 destBuffer[66]; // [rsp+458h] [rbp+350h] BYREF

  InstallPath = nullptr;
  FastMemset(destBuffer, 0, 0x208u);
  STATUS = RegReadValue(
             L"\\REGISTRY\\MACHINE\\SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{A9861883-31C5-4"
              "324-BD9A-DC9527EEB675}_is1",
             L"InstallLocation",
             &InstallPath);
  if ( STATUS >= 0 )
  {
    if ( !InstallPath )
      return 3221225473LL;
    v2 = *((_DWORD *)InstallPath + 2);
    if ( v2 >= 0x208 )
      return 3221225473LL;
    memmove(destBuffer, (char *)InstallPath + 12, v2);
    wcscpy(SourceString, L"\"");
    FastMemset((__int64 *)&SourceString[2], 0, 0x40Cu);
    v3 = (_WORD *)&InstallPath + 3;
    do
      ++v3;
    while ( *v3 );
    v4 = 0;
    do
    {
      v5 = *((_WORD *)destBuffer + v4);
      v3[v4++] = v5;
    }
    while ( v5 );
    v6 = (char *)&InstallPath + 6;
    do
      v6 += 2;
    while ( *(_WORD *)v6 );
    LODWORD(Data) = 2;
    *(_OWORD *)v6 = wszLenovoPc;
    *((_OWORD *)v6 + 1) = wszManagerS;
    *((_OWORD *)v6 + 2) = wzServiceExe;
    *((_QWORD *)v6 + 6) = 0x2200650078LL;
    CreateRegKey(L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoDRS");
    CreateRegKey(L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LAVService");
    CreateRegKey(L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoPcManagerService");
    RegWriteValue(L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoDRS", L"Start", 4u, &Data, 4u);
    RegWriteValue(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoPcManagerService",
      L"Start",
      4u,
      &Data,
      4u);
    RegWriteValue(L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LAVService", L"Start", 4u, &Data, 4u);
    v7 = -1;
    v8 = -1;
    do
      ++v8;
    while ( SourceString[v8] );
    RegWriteValue(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoPcManagerService",
      L"ImagePath",
      2u,
      SourceString,
      2 * v8 + 2);
    RegWriteValue(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoPcManagerService",
      L"Description",
      1u,
      descLenovoPcMgr,
      0x14u);
    RegWriteValue(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoPcManagerService",
      L"DisplayName",
      1u,
      L"LenovoPcManagerService",
      0x2Du);
    RegWriteValue(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoPcManagerService",
      L"ObjectName",
      1u,
      L"LocalSystem",
      0x16u);
    LODWORD(Data) = 16;
    RegWriteValue(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoPcManagerService",
      L"Type",
      4u,
      &Data,
      4u);
    RegWriteValue(L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoDRS", L"Type", 4u, &Data, 4u);
    RegWriteValue(L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LAVService", L"Type", 4u, &Data, 4u);
    LODWORD(Data) = 0;
    RegWriteValue(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoPcManagerService",
      L"ErrorControl",
      4u,
      &Data,
      4u);
    RegWriteValue(L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoDRS", L"ErrorControl", 4u, &Data, 4u);
    RegWriteValue(L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LAVService", L"ErrorControl", 4u, &Data, 4u);
    FastMemset((__int64 *)SourceString, 0, 0x208u);
    v9 = (_WORD *)&InstallPath + 3;
    do
      ++v9;
    while ( *v9 );
    *(_DWORD *)v9 = 34;
    v10 = (_WORD *)&InstallPath + 3;
    do
      ++v10;
    while ( *v10 );
    v11 = 0;
    do
    {
      v12 = *((_WORD *)destBuffer + v11);
      v10[v11++] = v12;
    }
    while ( v12 );
    v13 = (char *)&InstallPath + 6;
    do
      v13 += 2;
    while ( *(_WORD *)v13 );
    *(_OWORD *)v13 = xmmword_140002970;
    *((_QWORD *)v13 + 2) = 0x780065002E0053LL;
    *((_DWORD *)v13 + 6) = 2228325;
    *((_WORD *)v13 + 14) = 0;
    v14 = -1;
    do
      ++v14;
    while ( SourceString[v14] );
    RegWriteValue(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoDRS",
      L"ImagePath",
      2u,
      SourceString,
      2 * v14);
    RegWriteValue(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoDRS",
      L"Description",
      1u,
      descLenovoDRS,
      0x14u);
    RegWriteValue(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoDRS",
      L"DisplayName",
      1u,
      L"LenovoDRS",
      0x13u);
    RegWriteValue(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoDRS",
      L"ObjectName",
      1u,
      L"LocalSystem",
      0x17u);
    FastMemset((__int64 *)SourceString, 0, 0x208u);
    v15 = (_WORD *)&InstallPath + 3;
    do
      ++v15;
    while ( *v15 );
    *(_DWORD *)v15 = 34;
    v16 = (_WORD *)&InstallPath + 3;
    do
      ++v16;
    while ( *v16 );
    v17 = 0;
    do
    {
      v18 = *((_WORD *)destBuffer + v17);
      v16[v17++] = v18;
    }
    while ( v18 );
    v19 = (char *)&InstallPath + 6;
    do
      v19 += 2;
    while ( *(_WORD *)v19 );
    *(_OWORD *)v19 = wszServicePath_pt1;
    *((_OWORD *)v19 + 1) = wszServicePath_pt2;
    *((_OWORD *)v19 + 2) = wszServicePath_pt3;
    *((_OWORD *)v19 + 3) = wszServicePath_pt4;
    *((_DWORD *)v19 + 16) = 34;
    do
      ++v7;
    while ( SourceString[v7] );
    RegWriteValue(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LAVService",
      L"ImagePath",
      2u,
      SourceString,
      2 * v7);
    RegWriteValue(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LAVService",
      L"DependOnService",
      7u,
      L"RPCSS",
      0xAu);
    RegWriteValue(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LAVService",
      L"DisplayName",
      1u,
      L"LAVService",
      0x15u);
    RegWriteValue(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LAVService",
      L"ObjectName",
      1u,
      L"LocalSystem",
      0x17u);
    LODWORD(Data) = 1;
    LODWORD(v27) = 4;
    RegWriteConditional(
      L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LAVService",
      L"DelayedAutostart",
      4u,
      &Data,
      v27);
    FastMemset((__int64 *)SourceString, 0, 0x208u);
    v20 = (char *)&InstallPath + 6;
    do
      v20 += 2;
    while ( *(_WORD *)v20 );
    *(_OWORD *)v20 = *(_OWORD *)L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LAVService";
    *((_OWORD *)v20 + 1) = *(_OWORD *)L"Y\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LAVService";
    *((_OWORD *)v20 + 2) = *(_OWORD *)L"E\\SYSTEM\\ControlSet001\\Services\\LAVService";
    *((_OWORD *)v20 + 3) = *(_OWORD *)L"\\ControlSet001\\Services\\LAVService";
    *((_OWORD *)v20 + 4) = *(_OWORD *)L"Set001\\Services\\LAVService";
    *((_OWORD *)v20 + 5) = *(_OWORD *)L"ervices\\LAVService";
    *((_OWORD *)v20 + 6) = *(_OWORD *)L"LAVService";
    *((_DWORD *)v20 + 28) = *(_DWORD *)L"ce";
    *((_WORD *)v20 + 58) = aRegistryMachin_1[58];
    v21 = (char *)&InstallPath + 6;
    do
      v21 += 2;
    while ( *(_WORD *)v21 );
    *(_OWORD *)v21 = wszSecurityPathPrefix;
    *((_DWORD *)v21 + 4) = 121;
    CreateRegKey(SourceString);
    LODWORD(v28) = 224;
    RegWriteConditional(SourceString, L"Security", 3u, &SecurityDescriptorData, v28);
    FastMemset((__int64 *)SourceString, 0, 0x208u);
    v22 = (char *)&InstallPath + 6;
    do
      v22 += 2;
    while ( *(_WORD *)v22 );
    *(_OWORD *)v22 = *(_OWORD *)L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoDRS";
    *((_OWORD *)v22 + 1) = *(_OWORD *)L"Y\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoDRS";
    *((_OWORD *)v22 + 2) = *(_OWORD *)L"E\\SYSTEM\\ControlSet001\\Services\\LenovoDRS";
    *((_OWORD *)v22 + 3) = *(_OWORD *)L"\\ControlSet001\\Services\\LenovoDRS";
    *((_OWORD *)v22 + 4) = *(_OWORD *)L"Set001\\Services\\LenovoDRS";
    *((_OWORD *)v22 + 5) = *(_OWORD *)L"ervices\\LenovoDRS";
    *((_OWORD *)v22 + 6) = *(_OWORD *)L"LenovoDRS";
    *((_DWORD *)v22 + 28) = *(_DWORD *)L"S";
    v23 = (char *)&InstallPath + 6;
    do
      v23 += 2;
    while ( *(_WORD *)v23 );
    *(_OWORD *)v23 = wszSecurityPathPrefix;
    *((_DWORD *)v23 + 4) = 121;
    CreateRegKey(SourceString);
    LODWORD(v29) = 224;
    RegWriteConditional(SourceString, L"Security", 3u, &SecurityDescriptorData, v29);
    FastMemset((__int64 *)SourceString, 0, 0x208u);
    v24 = (char *)&InstallPath + 6;
    do
      v24 += 2;
    while ( *(_WORD *)v24 );
    *(_OWORD *)v24 = *(_OWORD *)L"\\REGISTRY\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoPcManagerService";
    *((_OWORD *)v24 + 1) = *(_OWORD *)L"Y\\MACHINE\\SYSTEM\\ControlSet001\\Services\\LenovoPcManagerService";
    *((_OWORD *)v24 + 2) = *(_OWORD *)L"E\\SYSTEM\\ControlSet001\\Services\\LenovoPcManagerService";
    *((_OWORD *)v24 + 3) = *(_OWORD *)L"\\ControlSet001\\Services\\LenovoPcManagerService";
    *((_OWORD *)v24 + 4) = *(_OWORD *)L"Set001\\Services\\LenovoPcManagerService";
    *((_OWORD *)v24 + 5) = *(_OWORD *)L"ervices\\LenovoPcManagerService";
    *((_OWORD *)v24 + 6) = *(_OWORD *)L"LenovoPcManagerService";
    v25 = v24 + 128;
    *((_OWORD *)v25 - 1) = *(_OWORD *)L"ManagerService";
    *(_QWORD *)v25 = *(_QWORD *)L"ervice";
    *((_DWORD *)v25 + 2) = *(_DWORD *)L"ce";
    *((_WORD *)v25 + 6) = aRegistryMachin_2[70];
    v26 = (char *)&InstallPath + 6;
    do
      v26 += 2;
    while ( *(_WORD *)v26 );
    *(_OWORD *)v26 = wszSecurityPathPrefix;
    *((_DWORD *)v26 + 4) = 121;
    CreateRegKey(SourceString);
    LODWORD(v30) = 224;
    RegWriteConditional(SourceString, L"Security", 3u, &SecurityDescriptorData, v30);
    ExFreePoolWithTag(InstallPath, 0);
  }
  return (unsigned int)STATUS;
}
// 140001689: variable 'v27' is possibly undefined
// 140001761: variable 'v28' is possibly undefined
// 140001822: variable 'v29' is possibly undefined
// 1400018EB: variable 'v30' is possibly undefined
// 140002670: using guessed type __int128 xmmword_140002670;
// 140002680: using guessed type __int128 xmmword_140002680;
// 140002690: using guessed type __int128 xmmword_140002690;
// 140002870: using guessed type __int64 qword_140002870[4];
// 1400028B0: using guessed type wchar_t aLenovopcmanage[23];
// 140002900: using guessed type wchar_t aLocalsystem[12];
// 140002970: using guessed type __int128 xmmword_140002970;
// 140002990: using guessed type __int64 qword_140002990[4];
// 1400029B0: using guessed type wchar_t aLenovodrs[10];
// 1400029D0: using guessed type __int128 xmmword_1400029D0;
// 1400029E0: using guessed type __int128 xmmword_1400029E0;
// 1400029F0: using guessed type __int128 xmmword_1400029F0;
// 140002A00: using guessed type __int128 xmmword_140002A00;
// 140002A20: using guessed type wchar_t aRpcss[6];
// 140002A50: using guessed type wchar_t aLavservice[11];
// 140002AA0: using guessed type __int128 xmmword_140002AA0;

//----- (0000000140001930) ----------------------------------------------------
void __fastcall StartRoutine(PVOID StartContext)
{
  unsigned int v1; // ebx

  v1 = 0;
  if ( KeGetCurrentIrql() )
    PsTerminateSystemThread(0);
  while ( !g_InstallDone )
  {
    if ( (int)InstallLenovoServices(StartContext) >= 0 )
      break;
    if ( v1 > 0xBB8 )
      break;
    ++v1;
    DelayMs(200);
  }
  g_InstallDone = 1;
  PsTerminateSystemThread(0);
}
// 140001950: variable 'StartContext' is possibly undefined
// 1400010B8: using guessed type __int64 __fastcall sub_1400010B8(_QWORD);
// 1400010E0: using guessed type __int64 __fastcall sub_1400010E0(_QWORD);
// 1400040F0: using guessed type char byte_1400040F0;

//----- (000000014000198C) ----------------------------------------------------
__int64 __fastcall TerminateProcess(HANDLE ProcessId)
{
  NTSTATUS STATUS; // ebx
  PEPROCESS Process; // [rsp+58h] [rbp+10h] BYREF
  HANDLE ProcessHandle; // [rsp+60h] [rbp+18h] BYREF

  Process = nullptr;
  ProcessHandle = nullptr;
  STATUS = PsLookupProcessByProcessId(ProcessId, &Process);
  if ( STATUS >= 0 )
  {
    STATUS = ObOpenObjectByPointer(Process, 0, nullptr, 0x1FFFFFu, nullptr, 0, &ProcessHandle);
    if ( STATUS >= 0 )
      STATUS = ZwTerminateProcess(ProcessHandle, 0);
  }
  if ( Process )
  {
    ObfDereferenceObject(Process);
    Process = nullptr;
  }
  if ( ProcessHandle )
    ZwClose(ProcessHandle);
  return (unsigned int)STATUS;
}

//----- (0000000140001A20) ----------------------------------------------------
void __fastcall RegWriteConditional(
        PCWSTR SourceString,
        PCWSTR ConditionalValueName,
        ULONG Type,
        PVOID Data,
        SIZE_T Length)
{
  PVOID v9; // rbx
  ULONG v10; // r14d
  PVOID P; // [rsp+50h] [rbp+8h] BYREF

  if ( SourceString )
  {
    P = nullptr;
    if ( ConditionalValueName )
    {
      if ( Data )
      {
        if ( (int)RegReadValue(SourceString, ConditionalValueName, &P) < 0 )
        {
          RegWriteValue(SourceString, ConditionalValueName, Type, Data, Length);
        }
        else
        {
          v9 = P;
          v10 = Length;
          if ( *((_DWORD *)P + 1) != Type
            || *((_DWORD *)P + 2) != (_DWORD)Length
            || RtlCompareMemory((char *)P + 12, Data, (unsigned int)Length) )
          {
            RegWriteValue(SourceString, ConditionalValueName, Type, Data, v10);
          }
          ExFreePoolWithTag(v9, 0);
        }
      }
    }
  }
}

//----- (0000000140001AEC) ----------------------------------------------------
__int64 __fastcall CreateRegKey(PCWSTR SourceString)
{
  NTSTATUS v3; // ebx
  struct _UNICODE_STRING DestinationString; // [rsp+40h] [rbp-40h] BYREF
  struct _OBJECT_ATTRIBUTES ObjectAttributes; // [rsp+50h] [rbp-30h] BYREF
  void *KeyHandle; // [rsp+90h] [rbp+10h] BYREF

  ObjectAttributes.Length = 0;
  FastMemset((__int64 *)&ObjectAttributes.RootDirectory, 0, 0x28u);
  DestinationString.Length = 0;
  *(_QWORD *)&DestinationString.MaximumLength = 0;
  *(_DWORD *)((char *)&DestinationString.Buffer + 2) = 0;
  HIWORD(DestinationString.Buffer) = 0;
  KeyHandle = nullptr;
  if ( !SourceString )
    return 3221225485LL;
  RtlInitUnicodeString(&DestinationString, SourceString);
  ObjectAttributes.ObjectName = &DestinationString;
  ObjectAttributes.Length = 48;
  ObjectAttributes.RootDirectory = nullptr;
  ObjectAttributes.Attributes = 576;
  *(_OWORD *)&ObjectAttributes.SecurityDescriptor = 0;
  v3 = ZwCreateKey(&KeyHandle, 0xF003Fu, &ObjectAttributes, 0, nullptr, 0, nullptr);
  if ( v3 >= 0 )
    ZwClose(KeyHandle);
  return (unsigned int)v3;
}

//----- (0000000140001BB4) ----------------------------------------------------
__int64 __fastcall RegReadValue(PCWSTR SourceString, PCWSTR a2, _QWORD *outBufPtr)
{
  PVOID allocBuf; // rdi
  NTSTATUS STATUS; // ebx
  NTSTATUS queryStatus; // eax
  struct _UNICODE_STRING ValueName; // [rsp+40h] [rbp-68h] BYREF
  struct _UNICODE_STRING DestinationString; // [rsp+50h] [rbp-58h] BYREF
  struct _OBJECT_ATTRIBUTES ObjectAttributes; // [rsp+60h] [rbp-48h] BYREF
  ULONG resultLen; // [rsp+B0h] [rbp+8h] BYREF
  void *KeyHandle; // [rsp+C8h] [rbp+20h] BYREF

  ObjectAttributes.Length = 0;
  FastMemset((__int64 *)&ObjectAttributes.RootDirectory, 0, 0x28u);
  DestinationString.Length = 0;
  *(_QWORD *)&DestinationString.MaximumLength = 0;
  *(_DWORD *)((char *)&DestinationString.Buffer + 2) = 0;
  HIWORD(DestinationString.Buffer) = 0;
  ValueName.Length = 0;
  *(_QWORD *)&ValueName.MaximumLength = 0;
  *(_DWORD *)((char *)&ValueName.Buffer + 2) = 0;
  HIWORD(ValueName.Buffer) = 0;
  allocBuf = nullptr;
  resultLen = 0;
  KeyHandle = nullptr;
  if ( !SourceString || !a2 || !outBufPtr )
    return 3221225485LL;
  RtlInitUnicodeString(&DestinationString, SourceString);
  RtlInitUnicodeString(&ValueName, a2);
  ObjectAttributes.Length = 48;
  ObjectAttributes.RootDirectory = nullptr;
  ObjectAttributes.Attributes = 576;
  ObjectAttributes.ObjectName = &DestinationString;
  *(_OWORD *)&ObjectAttributes.SecurityDescriptor = 0;
  STATUS = ZwOpenKey(&KeyHandle, 0x20019u, &ObjectAttributes);
  if ( STATUS >= 0 )
  {
    queryStatus = ZwQueryValueKey(KeyHandle, &ValueName, KeyValuePartialInformation, nullptr, 0, &resultLen);
    STATUS = queryStatus;
    if ( queryStatus >= 0 || queryStatus == -2147483643 || queryStatus == -1073741789 )
    {
      if ( resultLen )
      {
        allocBuf = ExAllocatePool((POOL_TYPE)512, resultLen);
        if ( allocBuf )
        {
          STATUS = ZwQueryValueKey(KeyHandle, &ValueName, KeyValuePartialInformation, allocBuf, resultLen, &resultLen);
          if ( STATUS >= 0 )
            *outBufPtr = allocBuf;
        }
        else
        {
          STATUS = -1073741670;
        }
      }
      else
      {
        STATUS = -1073741823;
      }
    }
  }
  if ( STATUS < 0 )
  {
    if ( allocBuf )
      ExFreePoolWithTag(allocBuf, 0);
    if ( KeyHandle )
      ZwClose(KeyHandle);
  }
  return (unsigned int)STATUS;
}

//----- (0000000140001DC0) ----------------------------------------------------
NTSTATUS __fastcall RegWriteValue(PCWSTR SourceString, PCWSTR RegValueName, ULONG Type, PVOID Data, ULONG InDataSize)
{
  ULONG DataSize; // ebx
  NTSTATUS result; // eax
  NTSTATUS v11; // ebx
  struct _UNICODE_STRING DestinationString; // [rsp+30h] [rbp-50h] BYREF
  struct _UNICODE_STRING ValueName; // [rsp+40h] [rbp-40h] BYREF
  struct _OBJECT_ATTRIBUTES ObjectAttributes; // [rsp+50h] [rbp-30h] BYREF
  void *KeyHandle; // [rsp+B0h] [rbp+30h] BYREF

  ObjectAttributes.Length = 0;
  FastMemset((__int64 *)&ObjectAttributes.RootDirectory, 0, 0x28u);
  DestinationString.Length = 0;
  *(_QWORD *)&DestinationString.MaximumLength = 0;
  *(_DWORD *)((char *)&DestinationString.Buffer + 2) = 0;
  HIWORD(DestinationString.Buffer) = 0;
  ValueName.Length = 0;
  *(_QWORD *)&ValueName.MaximumLength = 0;
  *(_DWORD *)((char *)&ValueName.Buffer + 2) = 0;
  HIWORD(ValueName.Buffer) = 0;
  KeyHandle = nullptr;
  if ( !SourceString )
    return -1073741811;
  if ( !RegValueName )
    return -1073741811;
  if ( !Data )
    return -1073741811;
  DataSize = InDataSize;
  if ( !InDataSize )
    return -1073741811;
  RtlInitUnicodeString(&DestinationString, SourceString);
  RtlInitUnicodeString(&ValueName, RegValueName);
  ObjectAttributes.Length = 48;
  ObjectAttributes.ObjectName = &DestinationString;
  ObjectAttributes.RootDirectory = nullptr;
  ObjectAttributes.Attributes = 576;
  *(_OWORD *)&ObjectAttributes.SecurityDescriptor = 0;
  result = ZwOpenKey(&KeyHandle, 0xF003Fu, &ObjectAttributes);
  if ( result >= 0 )
  {
    v11 = ZwSetValueKey(KeyHandle, &ValueName, 0, Type, Data, DataSize);
    if ( v11 >= 0 )
    {
      ZwFlushKey(KeyHandle);
      ZwClose(KeyHandle);
      return 0;
    }
    else
    {
      ZwClose(KeyHandle);
      return v11;
    }
  }
  return result;
}

//----- (0000000140001F20) ----------------------------------------------------
void __fastcall sub_140001F20(uintptr_t a1)
{
  __int64 v1; // rcx

  if ( a1 != _security_cookie )
LABEL_4:
    _report_gsfailure(a1);
  v1 = __ROL8__(a1, 16);
  if ( (_WORD)v1 )
  {
    a1 = __ROR8__(v1, 16);
    goto LABEL_4;
  }
}

//----- (0000000140002440) ----------------------------------------------------
// ---ANALYSIS_START---
// 
// ### Function Analysis
// 
// #### Use Environment:
// - This pseudo-code represents a function written in C language or a similar low-level programming language. It involves handling pointers and performing memory operations, which indicates that it is intended for a system-level application or environment where direct memory operations are necessary.
// 
// #### Expected Purpose:
// - The function appears to be designed to fill a block of memory, pointed to by `a1`, with a specific value, inferred from `a2`, up to a length specified by `a3`. This is similar to standard memory manipulation functions like `memset` in C.
// 
// #### Detailed Function Analysis:
// 1. **Parameters:**
//    - `__int64 *a1`: a pointer to the starting address of the memory block that needs to be filled.
//    - `__int64 a2`: the value to fill into the memory block.
//    - `unsigned __int64 a3`: the size/length of the memory block to fill.
// 
// 2. **Variable Definitions:**
//    - `result`: a copy of the pointer `a1`, which will likely be returned at the end.
//    - Various other variables (`v4`, `i`, `v6`, `v7`, `v8`, `j`) are used for loops, conditions, and intermediate calculations.
// 
// 3. **Logic Breakdown:**
//    - The function first checks if `a3` is less than 8. If true, it handles the filling in a specialized manner for the remaining bytes.
//    - If `a3` is not less than 8, the function calculates and sets `a2` for easy assignment into the memory. This may involve some bit manipulation for efficiency.
//    - The next portion of the code handles memory alignment; it aligns the memory to an 8-byte boundary if required.
//    - The main task of quickly filling memory in chunks of 8 bytes is then handled with a possible set of unrolled loops to optimize performance.
//    - The final segment adjusts for any remaining bytes that do not fit into the larger fill operations and fills them accordingly.
// 
// 4. **Function Flow:**
//    - Initial check for small memory ranges.
//    - Alignment of the memory block if necessary.
//    - Efficient filling of large chunks with loop unrolling.
//    - Handling of remaining bytes post main fill operation.
// 
// ### New Function Name:
// Considering the function's purpose and behavior, a more descriptive name would be `fast_memset`.
// 
// ---GPT_END---
// 
// This new name clearly indicates that the function is designed to rapidly set or fill a block of memory, similar to the behavior of `memset` but optimized perhaps for certain specific scenarios.
__int64 *__fastcall fast_memset(__int64 *a1, __int64 a2, unsigned __int64 a3)
{
  __int64 *result; // rax
  unsigned __int64 v4; // r9
  unsigned __int64 i; // r8
  unsigned int v6; // ecx
  __int64 *v7; // rcx
  unsigned __int64 v8; // r10
  unsigned __int64 j; // r8

  result = a1;
  if ( a3 < 8 )
  {
LABEL_5:
    for ( i = a3 & 7; i; --i )
      *((_BYTE *)a1 + i - 1) = a2;
    return result;
  }
  a2 = 0x101010101010101LL * (unsigned __int8)a2;
  if ( a3 < 0x47 )
  {
    v4 = a3 & 0x78;
    a1 = (__int64 *)((char *)a1 + (a3 & 0xFFFFFFFFFFFFFFF8uLL));
    do
    {
      *(__int64 *)((char *)result + v4 - 8) = a2;
      v4 -= 8LL;
    }
    while ( v4 );
    goto LABEL_5;
  }
  v6 = -(int)a1 & 7;
  if ( v6 )
  {
    a3 -= v6;
    *result = a2;
  }
  v7 = (__int64 *)((char *)result + v6);
  v8 = a3 >> 6;
  if ( ((a3 >> 3) & 7) != 0 )
    return ((__int64 *(__fastcall *)(__int64 *, __int64))((char *)&loc_1400024FD + 4 * (8 - ((a3 >> 3) & 7)) + 2))(
             &v7[((a3 >> 3) & 7) - 8],
             a2);
  do
  {
    *v7 = a2;
    v7[1] = a2;
    v7[2] = a2;
    v7[3] = a2;
    v7[4] = a2;
    v7[5] = a2;
    v7[6] = a2;
    v7[7] = a2;
    v7 += 8;
    --v8;
  }
  while ( v8 );
  for ( j = a3 & 7; j; --j )
    *((_BYTE *)v7 + j - 1) = a2;
  return result;
}
// 140002463: mask 0xFFFFFFFFFFFFFFF8 is shortened because r8.8 <= 0x46

//----- (0000000140007000) ----------------------------------------------------
NTSTATUS __stdcall DriverEntry(_DRIVER_OBJECT *DriverObject, PUNICODE_STRING RegistryPath)
{
  char v3; // di
  int v4; // ebx
  struct _UNICODE_STRING SymbolicLinkName; // [rsp+48h] [rbp-30h] BYREF
  struct _UNICODE_STRING DestinationString; // [rsp+58h] [rbp-20h] BYREF
  PDEVICE_OBJECT StartContext; // [rsp+80h] [rbp+8h] BYREF
  void *ThreadHandle; // [rsp+90h] [rbp+18h] BYREF

  ThreadHandle = nullptr;
  StartContext = nullptr;
  DriverObject->MajorFunction[4] = (PDRIVER_DISPATCH)DispatchCreateClose;
  DriverObject->MajorFunction[3] = (PDRIVER_DISPATCH)DispatchCreateClose;
  DriverObject->MajorFunction[2] = (PDRIVER_DISPATCH)DispatchCreateClose;
  DriverObject->MajorFunction[0] = (PDRIVER_DISPATCH)DispatchCreateClose;
  DriverObject->MajorFunction[16] = (PDRIVER_DISPATCH)DispatchShutdown;
  DriverObject->MajorFunction[14] = (PDRIVER_DISPATCH)DispatchDeviceControl;
  RtlInitUnicodeString(&DestinationString, L"\\Device\\::BootRepair");
  v3 = 0;
  v4 = IoCreateDevice(DriverObject, 0, &DestinationString, 0x22u, 0, 0, &StartContext);
  if ( v4 >= 0 )
  {
    v4 = PsCreateSystemThread(
           &ThreadHandle,
           0x1FFFFFu,
           nullptr,
           nullptr,
           nullptr,
           (PKSTART_ROUTINE)StartRoutine,
           nullptr);
    if ( v4 >= 0 )
    {
      RtlInitUnicodeString(&SymbolicLinkName, L"\\DosDevices\\BootRepair");
      v4 = IoCreateSymbolicLink(&SymbolicLinkName, &DestinationString);
      if ( v4 >= 0 )
      {
        v3 = 1;
        v4 = IoRegisterShutdownNotification(StartContext);
      }
    }
  }
  if ( v4 < 0 )
  {
    if ( v3 )
      IoDeleteSymbolicLink(&SymbolicLinkName);
    if ( StartContext )
      IoDeleteDevice(StartContext);
  }
  return v4;
}

// nfuncs=24 queued=14 decompiled=14 lumina nreq=0 worse=0 better=0
// ALL OK, 14 function(s) have been successfully decompiled
